sale/urls.py
from django.urls import path
from .import views
app_name="sale"
urlpatterns=[
    path("",views.index_view,name="index"),
    path("create/",views.create_view,name="create"),
    path("load/subcategories/",views.load_subcategories,name='load-subcategories'),
    path("create-brand/",views.create_brand_view,name="create-brand"),

    path("update/<slug>/",views.update_view,name='update'),
    path("delete/", views.delete_view, name="delete"),


    path("wish/", views.user_wishlist_view, name="wish"),
    path("wishlist/", views.wishlist_product_view, name="wishlist"),


    path("add/basket/", views.add_basket_view, name="add-basket"),
    path("basket/", views.basket_list_view, name="basket"),
   

    path("class/list/",views.ProductListView.as_view(),name="class/list")

]

setting/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("sale.urls")),
    path("accounts/",include("accounts.urls"))

]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sale/models.py
from distutils.command.upload import upload
from itertools import product
from pyexpat import model
from django.db import models
from django.contrib.auth import get_user_model
from .utils import *

User=get_user_model()

class BaseMixin(models.Model):
    slug=models.SlugField(unique=True,editable=False)
    created_at=models.DateTimeField(auto_now_add=True)
    updated_at=models.DateTimeField(auto_now=True)

    class Meta:
        abstract=True

class Category(BaseMixin):
    name=models.CharField(max_length=300)

    def __str__(self):
        return self.name or self.slug

    class Meta:
        ordering=("-created_at",)
        verbose_name="Category"
        verbose_name_plural="Categories"

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = create_slug_shortcode(size=12, model_=Category)

        super(Category, self).save(*args, **kwargs)


class Subcategory(BaseMixin):
    category=models.ForeignKey(Category,on_delete=models.CASCADE)
    name=models.CharField(max_length=300)

    def __str__(self):
        return self.name or self.slug

    class Meta:
        ordering=("-created_at",)
        verbose_name="Subcategory"
        verbose_name_plural="Subcategories"


    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = create_slug_shortcode(size=12, model_=Subcategory)

        super(Subcategory, self).save(*args, **kwargs)



class Brand(BaseMixin):
  
    name=models.CharField(max_length=300)

    def __str__(self):
        return self.name or self.slug

    class Meta:
        ordering=("-created_at",)
        verbose_name="Brand"
        verbose_name_plural="Brands"


    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = create_slug_shortcode(size=12, model_=Brand)

        super(Brand, self).save(*args, **kwargs)

class Product(BaseMixin):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=300)
    description = models.TextField(blank=True, null=True)
    subcategory = models.ForeignKey(Subcategory, on_delete=models.SET_NULL, blank=True, null=True)
    brand = models.ForeignKey(Brand, on_delete=models.SET_NULL, blank=True, null=True)
    
    wishlist=models.ManyToManyField(User,related_name='wishlist',blank=True)

    # price fields
    price = models.FloatField()
    tax_price = models.FloatField(blank=True, null=True)
    discount_price = models.FloatField(blank=True, null=True)

    def __str__(self):
        return self.name or self.slug

    class Meta:
        ordering = ("-created_at", )
        verbose_name = "Product"
        verbose_name_plural = "Products"


    def main_product_image(self):
        product_images = ProductImage.objects.filter(product=self)
        if product_images.exists():
            return product_images.first().image.url
        return '-'

    # def total_price(self):
    #     tax_price = self.tax_price if self.tax_price else 0
    #     discount_price = self.discount_price if self.discount_price else 0
    #     return self.price + tax_price - discount_price


    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = create_slug_shortcode(size=12, model_=Product)

        super(Product, self).save(*args, **kwargs)

def upload_to(instance,filename):
    return '%s/%s/%s'%('products',instance.product.name,filename)

class ProductImage(BaseMixin):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    image = models.ImageField(upload_to=upload_to)

    def __str__(self):
        return self.product.name or self.slug

    class Meta:
        ordering = ("-created_at", )
        verbose_name = "Product Image"
        verbose_name_plural = "Product Images"



    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = create_slug_shortcode(size=12, model_=ProductImage)

        super(ProductImage, self).save(*args, **kwargs)

   


class Basket(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return self.product.name

    class Meta:
        ordering = ("-id",)
        verbose_name = "Basket"
        verbose_name_plural = "Basket"

sale/forms.py
from django import forms
from .models import Brand, Product,Category, Subcategory


class ProductForm(forms.ModelForm):
    category=forms.ModelChoiceField(
        queryset=Category.objects.all()
    )
     


    class Meta:
        model=Product
        exclude=("user","subcategory", )


    def __init__(self,*args,**kwargs):
        super(ProductForm,self).__init__(*args,**kwargs)

        for field in self.fields:
            self.fields[field].widget.attrs.update({"class":"form-control"})




class ProductUpdateForm(forms.ModelForm):
    class Meta:
        model = Product
        exclude = ("user", "subcategory")

    def __init__(self, *args, **kwargs):
        super(ProductUpdateForm, self).__init__(*args, **kwargs)

        for field in self.fields:
            self.fields[field].widget.attrs.update({"class": "form-control"})

templates/products/create.html
{%extends 'base.html'%} 
{%load static%}
{%block title%}
<title>Create Page</title>
{%endblock%}
{%block body%}
<section class="mt-5">
    <div class="container">
       <h3 class="text-center">Create Page</h3>
       <form method="POST" class="px-5" enctype="multipart/form-data">
           {%csrf_token%}

           <div class="form-group mt-4">
            <label>{{product_form.name.label_tag}}</label><br/>
            {{product_form.name}}
           </div>
           <div class="form-group mt-4">
            <label>{{product_form.description.label_tag}}</label><br/>
            {{product_form.description}}
           </div>
           <div class="form-group mt-4">
            <label>{{product_form.brand.label_tag }}</label><br>
          
            <div class="input-group mb-3">
                {{ product_form.brand }}
                <div class="input-group-append">
                    <span class="input-group-text btn btn-warning"
                          data-bs-toggle="modal" data-bs-target="#createBrand">+</span>
                </div>
            </div>
        </div> 
           <div class="form-group mt-4">
            <label>{{product_form.category.label_tag}}</label><br/>
            {{product_form.category}}
           </div>
           <div class="form-group mb-2">
            <label class="mb-2">Subcategory</label><br>
            <select name="subcategory" id="id_subcategory" class="form-control">
                <option value="">---------</option>
            </select>
             </div>
           <div class="form-group mt-4">
            <label>{{product_form.price.label_tag}}</label><br/>
            {{product_form.price}}
           </div>
           <div class="form-group mt-4">
            <label>{{product_form.tax_price.label_tag}}</label><br/>
            {{product_form.tax_price}}
           </div>
           <div class="form-group mt-4">
            <label>{{product_form.discount_price.label_tag}}</label><br/>
            {{product_form.discount_price}}
           </div>
           <h4>Images</h4>
           <div class="form-group mb-4">
               <div id="imagesDiv" class="mb-4">
                   <input type="file" name="image" accept="image/png, image/gif, image/jpeg"/>
               </div>

               <a class="btn btn-primary" id="addImageButton" onclick="addImage()"> + </a>
           </div>



        
            <button type="submit" class="btn btn-success my-4">Create Product</button>
       </form>

    </div>

 <div class="modal fade" id="createBrand" tabindex="-1" role="dialog"
    aria-hidden="true">
   <div class="modal-dialog" role="document">
       <div class="modal-content">
           <div class="modal-header">
               <h5 class="modal-title" id="exampleModalLabel">Create New Brand</h5>
               <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
                   <span aria-hidden="true">&times;</span>
               </button>
           </div>
           <div class="modal-body">
               <form>
                   <div class="form-group">
                       <label class="mb-2">Brand Name</label>
                       <input type="text" class="form-control" name="brand_name" id="brand_name">
                       <p class="text-danger" style="display: none" id="brand-error">This field is required</p>
                   </div>
               </form>
           </div>
           <div class="modal-footer">
               <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
               <button type="button" class="btn btn-primary" id="createBrandBtn">Create Brand</button>
           </div>
       </div>
   </div>
 </div>
</section>
{%endblock%}

{%block js%}
<script>
        var load_subcategories_url = "{% url 'sale:load-subcategories' %}"
        var create_brand_url = "{% url 'sale:create-brand' %}"
</script>
<script>
        $("#id_category").change(function (event) {

var myHeaders = new Headers();
myHeaders.append(
    "X-CSRFToken",
    document.querySelector("[name=csrfmiddlewaretoken]").value
);

var formData = new FormData();

formData.append("category", event.target.value);

var requestOptions = {
    method: "POST",
    headers: myHeaders,
    body: formData,
    redirect: "follow",
};

response = fetch(load_subcategories_url, requestOptions).then(function (response) {
    if (response.ok) {
        response.json().then((data) => {
            var subcategories = data.subcategories

            $("#id_subcategory").html(`
            <option id="">---------</option>
            `)

            for (var i = 0; i < subcategories.length; i++) {
                            $("#id_subcategory").append(`
                                <option value="${subcategories[i]["id"]}">${subcategories[i]["name"]}</option>
                          `)
                        }
        });
    }
});
})



function addImage() {
            var image_inputs = $("input[type='file']").length


            if (image_inputs < 3) {
                $("#imagesDiv").append(`
                    <input type="file" name="image" accept="image/png, image/gif, image/jpeg" />
                `)
            }

            if (image_inputs >= 2) {
                $("#addImageButton").css("display", "none")
            }
        }


</script>



<script>
    $("#createBrandBtn").click(function (){
        var brand = $("#brand_name").val()

        if(brand){
            $("#brand-error").css("display", "none")
            $("#brand_name").css("border", "1px solid #ced4da")

            var myHeaders = new Headers();
            myHeaders.append(
                "X-CSRFToken",
                document.querySelector("[name=csrfmiddlewaretoken]").value
            );

            var formData = new FormData();

            formData.append("brand_name", brand);

            var requestOptions = {
                method: "POST",
                headers: myHeaders,
                body: formData,
                redirect: "follow",
            };

            response = fetch(create_brand_url, requestOptions).then(function (response) {
                if (response.ok) {
                    response.json().then((data) => {
                        $("#id_brand").append(`
                            <option value="${data.id}" selected>${data.name}</option>
                        `)
                        $("button[data-bs-dismiss='modal']").click()
                    });
                }
            });
        }else{
            $("#brand-error").css("display", "block")
            $("#brand_name").css("border", "2px solid red")
        }
    })
</script>
{%endblock%}

templates/products/update.html
{% extends "base.html" %}

{% block title %}
    <title>Create Page</title>
{% endblock %}

{% block body %}
    <section class="mt-5">
        <div class="container">
            <h1 class="text-center">Update Page</h1>

            <form method="POST" class="p-5" enctype="multipart/form-data">
                {% csrf_token %}

                <div class="form-group mb-2">
                    <label class="mb-2">{{ product_form.name.label_tag }}</label><br>
                    {{ product_form.name }}
                </div>

                <div class="form-group mb-2">
                    <label class="mb-2">{{ product_form.description.label_tag }}</label><br>
                    {{ product_form.description }}
                </div>

                <div class="form-group mb-2">
                    <label class="mb-2">{{ product_form.brand.label_tag }}</label><br>
                    <div class="input-group mb-3">
                        {{ product_form.brand }}
                        <div class="input-group-append">
                            <span class="input-group-text btn btn-warning"
                                  data-bs-toggle="modal" data-bs-target="#createBrand">+</span>
                        </div>
                    </div>
                </div>

                <div class="form-group mb-2">
                    <label class="mb-2">Cetegory</label><br>
                    <select name="subcategory" id="id_subcategory" class="form-control">
                        <option value="">---------</option>
                        {%for category in categories%}
                           <option value="{{category.id}}"
                           {%if product.subcategory.category == category %}selected
                           {%endif%}
                           >{{category.name}}</option>
                        {%endfor%}
                    </select>
                     </div>

                <div class="form-group mb-2">
                    <label class="mb-2">Subcategory</label><br>
                    <select name="subcategory" id="id_subcategory" class="form-control">
                        <option value="">---------</option>
                        {%for subcategory in product.subcategory.category.subcategory_set.all%}
                               <option value="{{subcategory.id}}"
                               {%if product.subcategory == subcategory %}selected
                               {%endif%}
                               >{{subcategory.name}}</option>
                        {%endfor%}
                    </select>
                </div>

                <div class="form-group mb-2">
                    <label class="mb-2">{{ product_form.price.label_tag }}</label><br>
                    {{ product_form.price }}
                </div>

                <div class="form-group mb-2">
                    <label class="mb-2">{{ product_form.tax_price.label_tag }}</label><br>
                    {{ product_form.tax_price }}
                </div>

                <div class="form-group mb-2">
                    <label class="mb-2">{{ product_form.discount_price.label_tag }}</label><br>
                    {{ product_form.discount_price }}
                </div>


                <h4>Images</h4> 
                <div id="imagesShow" class="row mb-4">
                    {% for product_image in product.productimage_set.all %}
                        <div style="width: 200px; height: 200px" class="col-4">
                            <img src="{{ product_image.image.url }}" alt="" style="width: 200px; height: 200px">
                        </div>
                    {% endfor %}
                </div>
                <div class="form-group mb-4">
                    <div id="imagesDiv" class="mb-4">
                        <input type="file" id="triggeredImage" name="image" accept="image/png, image/gif, image/jpeg" style="display:none;"/>
                        <span id="imageTrigger" class="btn btn-dark" >Choose Image</span>
                    </div>

                    <a class="btn btn-primary" id="addImageButton" onclick="addImage()"> + </a>
                </div>

                <button type="submit" class="btn btn-success btn-lg">Update Product</button>
            </form>
        </div>
    </section>



    <div class="modal fade" id="createBrand" tabindex="-1" role="dialog"
         aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Create New Brand</h5>
                    <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form>
                        <div class="form-group">
                            <label class="mb-2">Brand Name</label>
                            <input type="text" class="form-control" name="brand_name" id="brand_name">
                            <p class="text-danger" style="display: none" id="brand-error">This field is required</p>
                        </div>
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary" id="createBrandBtn">Create Brand</button>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block js %}

    <script>
        var load_subcategories_url = "{% url 'sale:load-subcategories' %}"
        var create_brand_url = "{% url 'sale:create-brand' %}"
    </script>
    <script>
        $("#imageTrigger").click(function(){
            $("#triggeredImage").click()
        })
    </script>

    <script>
        $("#id_category").change(function (event) {

            var myHeaders = new Headers();
            myHeaders.append(
                "X-CSRFToken",
                document.querySelector("[name=csrfmiddlewaretoken]").value
            );

            var formData = new FormData();

            formData.append("category", event.target.value);

            var requestOptions = {
                method: "POST",
                headers: myHeaders,
                body: formData,
                redirect: "follow",
            };

            response = fetch(load_subcategories_url, requestOptions).then(function (response) {
                if (response.ok) {
                    response.json().then((data) => {
                        var subcategories = data.subcategories

                        $("#id_subcategory").html(`
                        <option id="">---------</option>
                      `)

                        for (var i = 0; i < subcategories.length; i++) {
                            $("#id_subcategory").append(`
                                <option value="${subcategories[i]["id"]}">${subcategories[i]["name"]}</option>
                          `)
                        }
                    });
                }
            });
        })


        function addImage() {
            var image_inputs = $("input[type='file']").length


            if (image_inputs < 3) {
                $("#imagesDiv").append(`
                    <input type="file" name="image" accept="image/png, image/gif, image/jpeg" />
                `)
            }

            if (image_inputs >= 2) {
                $("#addImageButton").css("display", "none")
            }
        }
    </script>

    <script>
        $("#createBrandBtn").click(function (){
            var brand = $("#brand_name").val()

            if(brand){
                $("#brand-error").css("display", "none")
                $("#brand_name").css("border", "1px solid #ced4da")

                var myHeaders = new Headers();
                myHeaders.append(
                    "X-CSRFToken",
                    document.querySelector("[name=csrfmiddlewaretoken]").value
                );

                var formData = new FormData();

                formData.append("brand_name", brand);

                var requestOptions = {
                    method: "POST",
                    headers: myHeaders,
                    body: formData,
                    redirect: "follow",
                };

                response = fetch(create_brand_url, requestOptions).then(function (response) {
                    if (response.ok) {
                        response.json().then((data) => {
                            $("#id_brand").append(`
                                <option value="${data.id}" selected>${data.name}</option>
                            `)
                            $("button[data-bs-dismiss='modal']").click()
                        });
                    }
                });
            }else{
                $("#brand-error").css("display", "block")
                $("#brand_name").css("border", "2px solid red")
            }
        })
    </script>

{% endblock %}

templates/products/wishlist.html
{% extends "base.html" %}

{% block  title %}
    {{ block.super }}
{% endblock %}

{% block css %}
    <style>
        .btn-valeh {
            color: white;
            background-color: #d35400;
        }
    </style>
{% endblock %}

{% block body %}


    <section class="mt-5">
        {% csrf_token %}
        <div class="container">
            <h1 class="text-center">Wishlist Products</h1>

            {% if search %}
                <h5> Results for "{{ search }}" ( {{ products.count }} )</h5>
            {% endif %}


            <div id="products" class="align-items-center mt-5 row">
                {% for product in products %}
                    <div class="card mb-3 col-md-5 col-sm-12 mx-1" id="productDiv-{{ product.id }}">
                        <div class="row no-gutters">
                            <div class="col-md-4">
                                {% if product.productimage_set.all %}
                                    <img src="{{ product.main_product_image }}" class="card-img" alt="..."
                                         style="height: 200px; width: 180px;">
                                {% endif %}
                            </div>
                            <div class="col-md-8">
                                <div class="card-body">
                                    <h5 class="card-title">{{ product.name }}</h5>
                                    <p class="card-text">{{ product.description|safe }}</p>
                                    {% if request.user == product.user %}
                                    <a href="{% url 'sale:update' product.slug %}" class="text-warning">Edit</a>
                                    <a onclick="deleteProduct('{{ product.id }}')" class="text-danger"
                                    data-bs-toggle="modal" data-bs-target="#deleteModal"
                                       style="cursor:pointer;">Delete</a>
                                    {% endif %}
                                    <br><br>

                                    {% if request.user.is_authenticated %}
                                    <p onclick="addWishlist('{{ product.id }}')" id="wishDiv-{{ product.id }}" style="cursor:pointer ;">
                                        {% if request.user in product.wishlist.all %}
                                            <svg xmlns="http://www.w3.org/2000/svg" width="24" fill="#c0392b" height="24" viewBox="0 0 24 24"><path d="M12 4.248c-3.148-5.402-12-3.825-12 2.944 0 4.661 5.571 9.427 12 15.808 6.43-6.381 12-11.147 12-15.808 0-6.792-8.875-8.306-12-2.944z"/></svg>
                                        {% else %}
                                            <svg width="24" height="24" xmlns="http://www.w3.org/2000/svg" fill-rule="evenodd" clip-rule="evenodd"><path d="M12 21.593c-5.63-5.539-11-10.297-11-14.402 0-3.791 3.068-5.191 5.281-5.191 1.312 0 4.151.501 5.719 4.457 1.59-3.968 4.464-4.447 5.726-4.447 2.54 0 5.274 1.621 5.274 5.181 0 4.069-5.136 8.625-11 14.402m5.726-20.583c-2.203 0-4.446 1.042-5.726 3.238-1.285-2.206-3.522-3.248-5.719-3.248-3.183 0-6.281 2.187-6.281 6.191 0 4.661 5.571 9.429 12 15.809 6.43-6.38 12-11.148 12-15.809 0-4.011-3.095-6.181-6.274-6.181"/></svg>
                                        {% endif %}
                                    </p>

                                {%endif%}
                                    <br><br>
                                    <h5 class="card-text">{{ product.total_price|floatformat:2 }} AZN</h5>
                                    <p class="card-text"><small
                                            class="text-muted">Created {{ product.created_at|timesince }} ago</small>
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>

        </div>
    </section>

    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog"
         aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Delete Product</h5>
                    <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Back</button>
                    <button type="button" class="btn btn-danger" data-id="" id="deleteBtn">Delete</button>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

{% block js %}
    <script>
        var delete_url = "{% url 'sale:delete' %}"
        var wish_url = "{% url 'sale:wish' %}"
        var fill_heart_svg = `<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path d="M12 4.248c-3.148-5.402-12-3.825-12 2.944 0 4.661 5.571 9.427 12 15.808 6.43-6.381 12-11.147 12-15.808 0-6.792-8.875-8.306-12-2.944z"/></svg>`
        var heart_svg = `<svg width="24" height="24" xmlns="http://www.w3.org/2000/svg" fill-rule="evenodd" clip-rule="evenodd"><path d="M12 21.593c-5.63-5.539-11-10.297-11-14.402 0-3.791 3.068-5.191 5.281-5.191 1.312 0 4.151.501 5.719 4.457 1.59-3.968 4.464-4.447 5.726-4.447 2.54 0 5.274 1.621 5.274 5.181 0 4.069-5.136 8.625-11 14.402m5.726-20.583c-2.203 0-4.446 1.042-5.726 3.238-1.285-2.206-3.522-3.248-5.719-3.248-3.183 0-6.281 2.187-6.281 6.191 0 4.661 5.571 9.429 12 15.809 6.43-6.38 12-11.148 12-15.809 0-4.011-3.095-6.181-6.274-6.181"/></svg>`
    </script>

    <script>
        function deleteProduct(id){
            $("#deleteBtn").attr("data-id", id)
        }

        $("#deleteBtn").click(function (){
            var id = $(this).attr("data-id")

            var myHeaders = new Headers();
            myHeaders.append(
                "X-CSRFToken",
                document.querySelector("[name=csrfmiddlewaretoken]").value
            );

            var formData = new FormData();

            formData.append("id", id);

            var requestOptions = {
                method: "POST",
                headers: myHeaders,
                body: formData,
                redirect: "follow",
            };

            response = fetch(delete_url, requestOptions).then(function (response) {
                    if (response.ok) {
                        response.json().then((data) => {
                            // productun divini silmek
                            $("#productDiv-"+id).remove()
                            $("button[data-bs-dismiss='modal']").click()
                        });
                    }
                });
        })
    </script>


<script>
    function addWishlist(id){

        var myHeaders = new Headers();
        myHeaders.append(
            "X-CSRFToken",
            document.querySelector("[name=csrfmiddlewaretoken]").value
        );

        var formData = new FormData();

        formData.append("id", id);

        var requestOptions = {
            method: "POST",
            headers: myHeaders,
            body: formData,
            redirect: "follow",
        };

        response = fetch(wish_url, requestOptions).then(function (response) {
                if (response.ok) {
                    response.json().then((data) => {
                        console.log(data)
                        if(data.success){
                            $("#wishDiv-"+id).html(fill_heart_svg)
                        }else{
                            $("#wishDiv-"+id).html(heart_svg)
                        }
                    });
                }
            });
    }
</script>
{% endblock %}