accounts/urls.py
from django.urls import path
from . import views

app_name="accounts"
urlpatterns=[
    path("login/",views.login_view,name='login'),
    path("register/",views.register_view,name='register')
]

sale/urls.py
from django.urls import path
from .import views
app_name="sale"
urlpatterns=[
    path("",views.index_view,name="index"),
    path("create/",views.create_view,name="create"),
    path("load/subcategories/",views.load_subcategories,name='load-subcategories'),
    path("create-brand/",views.create_brand_view,name="create-brand"),

    path("update/<slug>/",views.update_view,name='update'),
    path("delete/", views.delete_view, name="delete"),


    path("wish/", views.user_wishlist_view, name="wish"),
    path("wishlist/", views.wishlist_product_view, name="wishlist"),


    path("add/basket/", views.add_basket_view, name="add-basket"),
    path("basket/", views.basket_list_view, name="basket"),
   

    path("class/list/",views.ProductListView.as_view(),name="class/list")

]

setting/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("sale.urls")),
    path("accounts/",include("accounts.urls"))

]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sale/models.py
from distutils.command.upload import upload
from itertools import product
from pyexpat import model
from django.db import models
from django.contrib.auth import get_user_model
from .utils import *

User=get_user_model()

class BaseMixin(models.Model):
    slug=models.SlugField(unique=True,editable=False)
    created_at=models.DateTimeField(auto_now_add=True)
    updated_at=models.DateTimeField(auto_now=True)

    class Meta:
        abstract=True

class Category(BaseMixin):
    name=models.CharField(max_length=300)

    def __str__(self):
        return self.name or self.slug

    class Meta:
        ordering=("-created_at",)
        verbose_name="Category"
        verbose_name_plural="Categories"

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = create_slug_shortcode(size=12, model_=Category)

        super(Category, self).save(*args, **kwargs)


class Subcategory(BaseMixin):
    category=models.ForeignKey(Category,on_delete=models.CASCADE)
    name=models.CharField(max_length=300)

    def __str__(self):
        return self.name or self.slug

    class Meta:
        ordering=("-created_at",)
        verbose_name="Subcategory"
        verbose_name_plural="Subcategories"


    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = create_slug_shortcode(size=12, model_=Subcategory)

        super(Subcategory, self).save(*args, **kwargs)



class Brand(BaseMixin):
  
    name=models.CharField(max_length=300)

    def __str__(self):
        return self.name or self.slug

    class Meta:
        ordering=("-created_at",)
        verbose_name="Brand"
        verbose_name_plural="Brands"


    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = create_slug_shortcode(size=12, model_=Brand)

        super(Brand, self).save(*args, **kwargs)

class Product(BaseMixin):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=300)
    description = models.TextField(blank=True, null=True)
    subcategory = models.ForeignKey(Subcategory, on_delete=models.SET_NULL, blank=True, null=True)
    brand = models.ForeignKey(Brand, on_delete=models.SET_NULL, blank=True, null=True)
    
    wishlist=models.ManyToManyField(User,related_name='wishlist',blank=True)

    # price fields
    price = models.FloatField()
    tax_price = models.FloatField(blank=True, null=True)
    discount_price = models.FloatField(blank=True, null=True)

    def __str__(self):
        return self.name or self.slug

    class Meta:
        ordering = ("-created_at", )
        verbose_name = "Product"
        verbose_name_plural = "Products"


    def main_product_image(self):
        product_images = ProductImage.objects.filter(product=self)
        if product_images.exists():
            return product_images.first().image.url
        return '-'

    # def total_price(self):
    #     tax_price = self.tax_price if self.tax_price else 0
    #     discount_price = self.discount_price if self.discount_price else 0
    #     return self.price + tax_price - discount_price


    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = create_slug_shortcode(size=12, model_=Product)

        super(Product, self).save(*args, **kwargs)

def upload_to(instance,filename):
    return '%s/%s/%s'%('products',instance.product.name,filename)

class ProductImage(BaseMixin):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    image = models.ImageField(upload_to=upload_to)

    def __str__(self):
        return self.product.name or self.slug

    class Meta:
        ordering = ("-created_at", )
        verbose_name = "Product Image"
        verbose_name_plural = "Product Images"



    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = create_slug_shortcode(size=12, model_=ProductImage)

        super(ProductImage, self).save(*args, **kwargs)

   


class Basket(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return self.product.name

    class Meta:
        ordering = ("-id",)
        verbose_name = "Basket"
        verbose_name_plural = "Basket"

templates/base.html
{%load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {%block title%}
    <title>Kontakt demo</title>
    {%endblock%}
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css" integrity="sha512-xh6O/CkQoPOWDdYTDqeRdPCVd1SpvCA9XXcUnZS2FmJNp1coAFzvtCN9BmamE+4aHK8yyUHUSCcJHgXloTyT2A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">

</head>
<body>
<div class="container">
    <nav class="navbar navbar-expand-lg ">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">Kontakt</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'sale:index' %}">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'sale:index' %}">Products</a>
              </li>
            
              <!-- <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="{% url 'sale:index' %}" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Product
                </a>
                <ul class="dropdown-menu">
                  <li><a class="dropdown-item" href="#">Action</a></li>
                  <li><a class="dropdown-item" href="#">Another action</a></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item" href="#">Something else here</a></li>
                </ul>
              </li> -->
              <li class="nav-item">
                <a class="nav-link" href="{%url 'sale:create'%}">Create</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Blog</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Contact</a>
              </li>
            </ul>
            <form class="d-flex" role="search">
               
              <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" id='search' name="search" {%if search %} value="{{search}}" {%endif%}>
            
              <button class="btn btn-outline-success" type="submit" name="sumbit_1">Search</button>
            </form>
            {%if search%}
            <p class="pt-4">{{search}}:{{products.count}}</p>
            {%endif%}
            <a href="{%url 'sale:wishlist'%}" class="my-4 mx-2" style="cursor:pointer;"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path d="M12 4.419c-2.826-5.695-11.999-4.064-11.999 3.27 0 7.27 9.903 10.938 11.999 15.311 2.096-4.373 12-8.041 12-15.311 0-7.327-9.17-8.972-12-3.27z"/></svg>
            </a>
            <a class="nav-link" href="{% url 'sale:basket' %}">
              <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path d="M10 19.5c0 .829-.672 1.5-1.5 1.5s-1.5-.671-1.5-1.5c0-.828.672-1.5 1.5-1.5s1.5.672 1.5 1.5zm3.5-1.5c-.828 0-1.5.671-1.5 1.5s.672 1.5 1.5 1.5 1.5-.671 1.5-1.5c0-.828-.672-1.5-1.5-1.5zm1.336-5l1.977-7h-16.813l2.938 7h11.898zm4.969-10l-3.432 12h-12.597l.839 2h13.239l3.474-12h1.929l.743-2h-4.195z"/></svg>
          
              <span class="text-danger" style="font-weight: bold; font-size: 16px;"
                    id="basket_counter">{{ basket_count }}</span></a>
              <a href="{% url 'accounts:register' %}">
                <i class="fa-solid fa-right-to-bracket mx-2"></i>
              </a>
             
              <a href="{% url 'accounts:login' %}">
                <i class="fa-solid fa-user mx-2"></i>
              </a>


             
          </div>
        </div>
      </nav>


</div>
  


    {% block body %}
    {% endblock %}
    


    <!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>

<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
<script src="https://code.jquery.com/jquery-3.1.0.min.js"></script>
<script src='https://code.jquery.com/jquery-3.2.1.min.js'></script>


{%block js%}

{%endblock%}
</body>
</html>

templates/index.html
{%extends 'base.html'%} {%load static%} {%block title%}
<title>Index Page</title>
{%endblock%} {%block body%}

<div class="text-center my-5">
  <h1>All Products</h1>
</div>
<div class="w-100 d-flex justify-content-between">
  <div class="container">
    <div class="col-lg-12 d-flex justify-content-between">
      <div class="col-lg-3">
        <h2 class="text-center">
          Filters
          <hr />
        </h2>
        <div
          class="col-lg-12 d-flex justify-content-between p-3 border border-succes"
        >
          <form action="" method="get">
            <div class="col-lg-12">
              <label
                >Min price
                <input
                  type="number"
                  id="min_price"
                  name="min_price"
                  class="form-control"
                  {%if min_price%}
                  value="{{min_price}}"
                  {%endif%}
                />
              </label>
            </div>
            <div class="col-lg-12 my-3">
              <label
                >Max price
                <input
                  type="number"
                  id="max_price"
                  name="max_price"
                  class="form-control"
                  {%if max_price%}
                  value="{{max_price}}"
                  {%endif%}
                />
              </label>
            </div>
            <button
              class="btn btn-outline-success"
              type="submit"
              name="button_2"
            >
              Search
            </button>
          </form>
        </div>
        <div class="col-lg-12 border p-3 mt-3">
          <form
            action=""
            method="get"
            class="d-flex justify-content-between align-items-center"
          >
            <span>Filterle</span>
            <button
              class="btn btn-outline-success"
              type="submit"
              name="button_3"
            >
              Search
            </button>
         

          {% for category in categories%}
          <span><b>{{category.name}}</b></span>

            {%for subcategory in category.subcategory_set.all%}
            <div class="filter">
              <span class="py-1">{{subcategory.name}}</span>
              <input type="checkbox" name="subcategory" value="{{subcategory.id}}"
              {% if selected_subcategory == subcategory.id %} checked {% endif %}/><br />
            </div>

            {%endfor%} 
          {%endfor%}
        </form>
        </div>
      </div>
      <div class="col-lg-9 d-flex flex-wrap ps-5">
        {%for product in products%}
        <div class="col-lg-6 px-1">
          <div class="card mb-1" style="max-width: 540px;">
            <div class="row g-0">
              <div class="col-md-4">
                {% if product.productimage_set.all %}
                <!-- <h1>{{product.productimage_set.all}}</h1> -->
                <!-- <h1>{{product.main_product_image}}</h1> -->
                <img
                  src="{{ product.main_product_image }}"
                  class="card-img mt-4"
                  alt="..."
                 
                />
                {% endif %}
              </div>
              <div class="col-md-8">
                <div class="card-body">
                  <h5 class="card-title">{{product.name}}</h5>
                  <p class="card-text">{{product.description|safe}}</p>
                  <p class="card-text">{{product.tax_float_price}}</p>
                  <h6>{{product.total_price|floatformat:2}}</h6>
                  <p class="card-text">
                    <small class="text-muted"
                      >Created {{product.created_at|timesince}}</small
                    >
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
        {%endfor%}
      </div>

    </div>
    <div>
      {% if paginator.num_pages > 1 %}
      <nav aria-label="Page navigation example">
          <ul class="pagination justify-content-center">
              {% if products.has_previous %}
                  <li class="page-item"><a class="page-link bg-dark text-light"
                                           href="?page={{ products.previous_page_number }}">
                      <
                  </a></li>
              {% endif %}
              {% for i in products.paginator.page_range %}
                  {% if products.number == i %}
                      <li class="page-item active"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
                  {% elif products.number != i %}
                      <li class="page-item"><a class="page-link" href="?page=
                              {{ i }}{% if search %}&search={{ search }}{% endif %}">{{ i }}</a></li>
                  {% endif %}
              {% endfor %}
              {% if products.has_next %}
                  <li class="page-item"><a class="page-link bg-dark text-light"
                                           href="?page={{ products.next_page_number }}">
                      >
                  </a></li>
              {% endif %}
          </ul>
      </nav>
      {% endif %}
    </div>
  </div>
</div>

{%endblock%}

templates/product.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    <title>Product Page</title>
{% endblock %}
{% block body %}

    <div class="text-center my-5">
        <h1>All Products</h1>
    </div>
    <div class="w-100 d-flex justify-content-between">
        <div class="container">
            <div class="col-lg-12 d-flex justify-content-between">
                <div class="col-lg-3">
                    <form action="" method="get">
                        <h2 class="text-center">
                            Filters
                            <hr/>
                        </h2>
                        <div class="col-lg-12 row d-flex justify-content-between p-3 border border-succes">
                                <div class="col-12">
                                    <label>Min price
                                        <input type="number" id="min_price"
                                               name="min_price" class="form-control"
                                                {% if min_price %}value="{{ min_price }}"{% endif %}/>
                                    </label>
                                </div>
                                <div class="col-12 my-3">
                                    <label>Max price
                                        <input type="number" id="max_price" name="max_price"
                                                class="form-control"
                                                {% if max_price %}value="{{ max_price }}"{% endif %}/>
                                    </label>
                                </div>
                                <button class="btn btn-outline-success col-6 mx-3"
                                        type="submit">
                                    Search
                                </button>
                        </div>
                        <div class="col-lg-12 border p-3 mt-3">
                                <span>Filterle</span>
                                <button
                                        class="btn btn-outline-success"
                                        type="submit"
                                >
                                    Search
                                </button>
                            <br><br>

                            {% for category in categories %}
                                <span><b>{{ category.name }}</b></span>

                                {% for subcategory in category.subcategory_set.all %}
                                    <div class="filter">
                                        <span class="py-1">{{ subcategory.name }}</span>
                                        <input type="checkbox" name="subcategory" value="{{ subcategory.id }}"
                                                {% if subcategory.id in selected_subcategories %} checked {% endif %}/><br/>
                                    </div>

                                {% endfor %}
                            {% endfor %}
                        </div>
                    </form>
                </div>
                <div class="col-lg-9 d-flex flex-wrap ps-5">
                    {% for product in products %}
                        <div class="col-lg-6 px-1">
                            <div class="card mb-1" style="max-width: 540px;">
                                <div class="row g-0">
                                    <div class="col-md-4">
                                        {% if product.productimage_set.all %}
                                            <!-- <h1>{{product.productimage_set.all}}</h1> -->
                                            <!-- <h1>{{product.main_product_image}}</h1> -->
                                            <img
                                                    src="{{ product.main_product_image }}"
                                                    class="card-img mt-4"
                                                    alt="..."

                                            />
                                        {% endif %}
                                    </div>
                                    <div class="col-md-8">
                                        <div class="card-body">
                                            <h5 class="card-title">{{ product.name }}</h5>
                                            <p class="card-text">{{ product.description|safe }}</p>
                                            <p class="card-text">{{ product.tax_float_price }}</p>
                                            <h6>{{ product.total_price|floatformat:2 }}</h6>
                                            <p class="card-text">
                                                <small class="text-muted"
                                                >Created {{ product.created_at|timesince }}</small
                                                >
                                            </p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>

            </div>
            <div>
                {% if paginator.num_pages > 1 %}
                    <nav aria-label="Page navigation example">
                        <ul class="pagination justify-content-center">
                            {% if products.has_previous %}
                                <li class="page-item"><a class="page-link bg-dark text-light"
                                                         href="?page={{ products.previous_page_number }}">
                                    <
                                </a></li>
                            {% endif %}
                            {% for i in products.paginator.page_range %}
                                {% if products.number == i %}
                                    <li class="page-item active"><a class="page-link" href="?page={{ i }}">{{ i }}</a>
                                    </li>
                                {% elif products.number != i %}
                                    <li class="page-item"><a class="page-link" href="?page=
                              {{ i }}{% if search %}&search={{ search }}{% endif %}">{{ i }}</a></li>
                                {% endif %}
                            {% endfor %}
                            {% if products.has_next %}
                                <li class="page-item"><a class="page-link bg-dark text-light"
                                                         href="?page={{ products.next_page_number }}">
                                    >
                                </a></li>
                            {% endif %}
                        </ul>
                    </nav>
                {% endif %}
            </div>
        </div>
    </div>

{% endblock %}